package com.jb.junit;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
class SortingArrayTest {
	@Test
	void test() {
		try {
		SortingArray array=new SortingArray();
		int[] unsorted = {30,10,20,02};
//		int[] unsorted = null; // if null, the array not execute it throws an exception
		int[] sordedArray = array.sortingArray(unsorted);
		for(int x: sordedArray)
		{
			System.out.println(x);
		}
		fail();//failing the testcase explicitly even though it is correct, so the catch block is executed
		}
		catch (Exception e) // here to say the test case is passed and that methods throws an exception (array can't accept null for sorting)
		{
			System.out.println("The Exception is "+ e); 
		}
	}

}
